---
title: "tax_analysis"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(ISLR)
library(tigris)
library(leaflet)
```

```{r message=FALSE, warning=FALSE}
audits <- here::here("data/cleaned/auditsData_2019.04.03.csv") %>%
    read_csv()
race_county <- here::here("data/cleaned/race_eth_county.csv") %>%
    read_csv()
incomes <- here::here("data/cleaned/incomes.csv") %>%
    read_csv()
joined <- full_join(audits, race_county, by = "fips") %>%
  full_join(., incomes, by = "fips") %>% 
  select(fips, state.x, county, n_returns, estimated_exams, audit_rate, white, black, indian, asian, hawaiian, other, two, non_his, hispanic, median_income) 
```

```{r}
joined <- joined %>%
  mutate(non_white = black + indian + asian + hawaiian + other + two, 
         pred_white = as.logical(ifelse(white >= non_white, 1, 0)))
```


```{r}
fit = lm(audit_rate ~ pred_white + median_income, data = joined)
summary(fit)
```

```{r}
# For predominantly non-white counties $y = -.00002935x + 10.35$
# For predominantly white counties, $y = -.00002935x + 9.23$
```


```{r}
ggplot(data = joined, aes(x = county, y = audit_rate, color = pred_white)) +
  geom_point() 
```

```{r}
ggplot(data = joined, aes(x = median_income, y = audit_rate, color = pred_white)) +
  geom_point() + 
  geom_smooth(method = "lm")
```


```{r}
ggplot(data = joined, aes(x = median_income, y = audit_rate, color = pred_white)) +
  geom_point() +
  stat_function(fun = function(x) -.00002935*x + 10.35) +
  stat_function(fun = function(x) -.00002935*x + 9.23)
```

```{r}
better_fit = lm(audit_rate ~ poly(median_income, 2, raw = TRUE) + pred_white, data = joined)
summary(better_fit)
```

```{r}
ggplot(joined, aes(x = median_income, y = audit_rate, color = pred_white)) +
  geom_point() +
  stat_smooth(method = lm, formula = y ~ poly(x, 2, raw = TRUE))
```

```{r}
better_fit2 = lm(audit_rate ~ poly(pred_white, 3, raw = TRUE) + median_income, data = joined)
summary(better_fit2)
```

```{r}
ggplot(joined, aes(x = median_income, y = audit_rate, color = pred_white)) +
  geom_point() +
  stat_smooth(method = lm, formula = y ~ poly(x, 3, raw = TRUE))
```

```{r}
joined <- joined %>% 
  mutate(pred_white2 = factor(pred_white, labels = c("People of Color", "White")))

plot_all <- ggplot(data = joined, aes(x = median_income, y = audit_rate, color = pred_white2)) +
  geom_point() + 
  geom_smooth(method = lm, color = "#f9766e") +
  stat_smooth(method = lm, formula = y ~ poly(x, 2, raw = TRUE), color = "#7caf00") +
  stat_smooth(method = lm, formula = y ~ poly(x, 3, raw = TRUE), color = "#c77cff") +
  scale_x_continuous(labels = scales::dollar) +
  scale_y_continuous(labels = function(x) paste0(x, '%')) +
  # scale_color_discrete(levels = c("People of Color", "White", "Racial Data not Available")) +
  labs(x = "Median Income",
       y = "Percent of Tax Returns Audited",
       title = "",
       subtitle = "Each point represents one US county", 
       color = "Predominant Racial Identity")



plot_all
```

```{r}
cnty <- counties(state = FALSE, cb = TRUE, resolution = "20m")
cnty <- cnty %>% 
  unite(fips, c(STATEFP, COUNTYFP), sep = "", remove = FALSE) %>%
  mutate(fips = str_remove(fips, "^0+"), 
         fips = as.numeric(fips))

joined_cnty <- full_join(cnty, joined, by = "fips")

pal1 <- colorNumeric(palette = "YlOrRd", domain = joined_cnty$audit_rate)

pal2 <- colorNumeric(palette = "YlGnBu", domain = joined_cnty$median_income)

pal3 <- colorFactor(palette = c("grey34","grey88"), domain = joined_cnty$pred_white2)
```

```{r}
leaflet(joined_cnty) %>%
  addTiles() %>%
  addPolygons(group = "Percentage of Taxes Audited",
              fillColor = ~pal1(audit_rate), 
              color = "#b2aeae", # use hex colors for line color
              fillOpacity = 0.7, 
              weight = 1, 
              smoothFactor = 0.2,
              popup = ~ paste(county, state.x)) %>%
  addPolygons(group = "Median Income",
              fillColor = ~pal2(median_income),
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7,
              weight = 1,
              smoothFactor = 0.2,
              popup = ~ paste(county, state.x)) %>%
    addPolygons(group = "Racial Identity",
              fillColor = ~pal3(pred_white2),
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7,
              weight = 1,
              smoothFactor = 0.2,
              popup = ~ paste(county, state.x)) %>%
  addLegend(pal = pal1, 
            values = joined_cnty$audit_rate, 
            position = "topright", 
            title = "Percent of Taxes Audited",
            labFormat = labelFormat(suffix = "%")) %>%
  addLegend(pal = pal2, 
            values = joined_cnty$median_income, 
            position = "topright", 
            title = "Median Income") %>%
  addLayersControl(
    overlayGroups = c("Percentage of Taxes Audited", "Median Income", "Racial Identity"),
    options = layersControlOptions(collapsed = FALSE)
  )

```

```{r}
joined_cnty <- na.omit(joined_cnty)
```






